### ISSUE TITLE
Not working while on proxy

### ISSUE THREAD

**Issue by priyanshu-shubham** [bjesus/muxile#2]
This is a great program but I am not able to run it on my institute wifi, possibly because it requires a proxy!? Can you help me with it?

**Comment by bjesus** [comment]
Thanks @priyanshu-shubham !
are you getting any specific errors? what's failing exactly? it doesn't really require a proxy server, it simply uses WebSockets to connect to a remote server. Perhaps your institute is blocking WebSocket connections?

If you need to configure a proxy server, see this: https://github.com/vi/websocat/issues/15
