### ISSUE TITLE
Unable to see the output on web browser.

### ISSUE THREAD

**Issue by vquyen-study** [bjesus/muxile#5]
Hi,

It is great feature for tmux.
But when I tried to setup follow your setup but the session does not work properly. I tried with generated link, but it is not show any text or result of tmux session.
Below is my setup steps:
1. The setup muxile was done with tmp (plugin manager).
2. It is able to create the QR code or link to open in browser.
3. Click  on the link to open in browser but the screen have nothing. But I was able to input the text in last editing text aread

I attached image as below.
![tmux-share-screen-failure](https://github.com/bjesus/muxile/assets/87596502/cb6dc014-3a6e-4829-8bdc-82d3bb02c3e6)

Thanks in advance!

**Comment by bjesus** [comment]
after pressing enter, does `ls -la` run in your terminal?

**Comment by vquyen-study** [comment]
Hi Bjesus,

There is nothing update on the screen, the above image is just on web browser.
In my local tmux session, it keeps in QR code & link on the screen.

Is there any debug log, that I can provide for more clearer problem.

Thanks.

**Comment by bjesus** [comment]
As per the README, after seeing the QR code and scanning it with your phone you need to: "go back to your terminal with `Ctrl+C`". Are you doing that?

**Comment by bjesus** [comment]
closed for no response
