### ISSUE TITLE
With every action I do, ".../emmiter.sh returns 1"

### ISSUE THREAD

**Issue by alr86** [bjesus/muxile#6]
[Kooha-2024-07-12-19-03-06.webm](https://github.com/user-attachments/assets/d2978c76-18aa-40fa-80fd-ddd179c74c2b)

OS: Arch linux

**Comment by bjesus** [comment]
are you sure you have installed all the dependencies from the [Requirements](https://github.com/bjesus/muxile?tab=readme-ov-file#requirements) section?

**Comment by alr86** [comment]
Aw yes, I didn't have websocat installed!😅

And please add the `set-g @plugin 'bjesus/muxile'` command to the README to make it easier to install🙏
